#!/bin/sh

cp .env.example .env

HYDRUSRV_CONTENT_DB_PATH="${HYDRUSRV_CONTENT_DB_PATH:=/data/content.db}"
HYDRUS_SERVER_DB_PATH="${HYDRUS_SERVER_DB_PATH:=/data/server.db}"
HYDRUS_MASTER_DB_PATH="${HYDRUS_MASTER_DB_PATH:=/data/server.master.db}"
HYDRUS_MAPPINGS_DB_PATH="${HYDRUS_MAPPINGS_DB_PATH:=/data/server.mappings.db}"
HYDRUS_TAG_REPOSITORY="${HYDRUS_TAG_REPOSITORY:=2}"
HYDRUS_FILE_REPOSITORY="${HYDRUS_FILE_REPOSITORY:=3}"
HYDRUS_SUPPORTED_MIME_TYPES="${HYDRUS_SUPPORTED_MIME_TYPES:=1,2,3,4,9,14,18,20,21,23,25,26,27}"
DOCKER_CRON_SCHEDULE="${DOCKER_CRON_SCHEDULE:=0 4 * * *}"

sed -i "s~HYDRUSRV_CONTENT_DB_PATH=~HYDRUSRV_CONTENT_DB_PATH=$HYDRUSRV_CONTENT_DB_PATH~g" .env
sed -i "s~HYDRUS_SERVER_DB_PATH=~HYDRUS_SERVER_DB_PATH=$HYDRUS_SERVER_DB_PATH~g" .env
sed -i "s~HYDRUS_MASTER_DB_PATH=~HYDRUS_MASTER_DB_PATH=$HYDRUS_MASTER_DB_PATH~g" .env
sed -i "s~HYDRUS_MAPPINGS_DB_PATH=~HYDRUS_MAPPINGS_DB_PATH=$HYDRUS_MAPPINGS_DB_PATH~g" .env
sed -i "s~HYDRUS_TAG_REPOSITORY=2~HYDRUS_TAG_REPOSITORY=$HYDRUS_TAG_REPOSITORY~g" .env
sed -i "s~HYDRUS_FILE_REPOSITORY=3~HYDRUS_FILE_REPOSITORY=$HYDRUS_FILE_REPOSITORY~g" .env
sed -i "s~HYDRUS_SUPPORTED_MIME_TYPES=1,2,3,4,9,14,18,20,21,23,25,26,27~HYDRUS_SUPPORTED_MIME_TYPES=$HYDRUS_SUPPORTED_MIME_TYPES~g" .env

sed -i "s~DOCKER_CRON_SCHEDULE~$DOCKER_CRON_SCHEDULE~g" ./crontab

stop() {
  pkill supercronic
  sleep 1
}

trap "stop" SIGTERM

echo "waiting 60 seconds before running initial sync..."

sleep 60

node ./bin/sync

supercronic ./crontab &

wait $!
